### ISSUE TITLE
Incorrect use of deno env()

### ISSUE THREAD

**Issue by zhmushan** [zhmushan/deno_path#1]
* OS: win
* [code](https://github.com/zhmushan/deno_path/blob/master/index.ts#L138)

In deno, `env` is a function, not a variable.
This is caused by my mistake review, it should be fixed.

**Comment by wanf3ng** [comment]
fix bug

In deno, `env` is a function, not a variable. So the line 138 of  `index.ts` change to :
 `path = env()['=' + resolvedDevice] || cwd()` 

Closes #1
